apiVersion: v1
kind: ConfigMap
metadata:
  name: fleksitask-backend-config
  namespace: fleksitask
data:
  DEBUG: "false"
  MEDIA_DIR: "/app/media"
  MAX_UPLOAD_SIZE_MB: "5"
  ALLOWED_ORIGINS: '["https://fleksitask.com","https://admin.fleksitask.com"]'
